name: Terraform Plan + Checkov Policy Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary
        env:
          TF_VAR_account_id: "123456789012"
          TF_VAR_ci_account_id: "111111111111"

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: environments/dev
          framework: terraform
          soft_fail: false